name: Cloud Deploy Automation

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  id-token: write

env:
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::325774504337:role/github-actions-ecr-role
          aws-region: eu-central-1

      - name: ECR Login
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: docker build -t my-app:${{ github.sha }} .

      - name: Tag Docker image
        run: docker tag my-app:${{ github.sha }} 325774504337.dkr.ecr.eu-central-1.amazonaws.com/my-app:${{ github.sha }}

      - name: Push Docker image
        run: docker push 325774504337.dkr.ecr.eu-central-1.amazonaws.com/my-app:${{ github.sha }}

      - name: Run command via SSM
        run: |
          aws ssm send-command \
            --instance-ids i-0e028c261508c5b76 \
            --document-name "AWS-RunShellScript" \
            --parameters 'commands=["echo Hello from SSM"]'
